# Generated by Django 3.2.16 on 2024-06-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Уникальный индификатор')),
                ('picture', models.ImageField(default=None, null=True, upload_to='recipes/picture/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='UnderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Уникальный индификатор')),
                ('picture', models.ImageField(default=None, null=True, upload_to='recipes/picture/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'ПодКатегория',
                'verbose_name_plural': 'ПодКатегории',
            },
        ),
        migrations.CreateModel(
            name='CategoryToUnderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='сategory', to='products.category', verbose_name='Ид Категории')),
                ('id_under_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_category', to='products.undercategory', verbose_name='Ид Под Категории')),
            ],
            options={
                'verbose_name': 'Пересеение Категории и Под Категории',
                'verbose_name_plural': 'Все пересеения Категории и Под Категории',
            },
        ),
    ]
