# Generated by Django 3.2.16 on 2024-06-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_size_1', models.ImageField(default=None, null=True, upload_to='recipes/size_1/', verbose_name='Размер картинки 1')),
                ('picture_size_2', models.ImageField(default=None, null=True, upload_to='recipes/size_2/', verbose_name='Размер картинки 2')),
                ('picture_size_3', models.ImageField(default=None, null=True, upload_to='recipes/size_3/', verbose_name='Размер картинки 3')),
            ],
            options={
                'verbose_name': 'Колекция картинок для продукта',
                'verbose_name_plural': 'Все колекции картинок для продуктов',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Индификатор'),
        ),
        migrations.AlterField(
            model_name='undercategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Индификатор'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Индификатор')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('all_image_sizes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_image_sizes', to='products.sizeimage', verbose_name='Отношениям ковсем размерам картинок')),
                ('current_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_category', to='products.categorytoundercategory', verbose_name='Отношениям к катигориям')),
            ],
        ),
    ]
