# Generated by Django 3.2.16 on 2024-06-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20240627_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='all_image_sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_image_sizes', to='products.sizeimage', verbose_name='Отношениям ковсем размерам картинок'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.products', verbose_name='Отношениям ковсем размерам картинок')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_user', to=settings.AUTH_USER_MODEL, verbose_name='Корзина пользователя')),
            ],
        ),
    ]
