# Generated by Django 3.2.16 on 2024-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240628_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undercategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='сategory', to='products.category'),
        ),
    ]
