# Generated by Django 3.2.16 on 2024-06-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_undercategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizeimage',
            old_name='picture_size_1',
            new_name='size_1',
        ),
        migrations.RenameField(
            model_name='sizeimage',
            old_name='picture_size_2',
            new_name='size_2',
        ),
        migrations.RenameField(
            model_name='sizeimage',
            old_name='picture_size_3',
            new_name='size_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='all_image_sizes',
        ),
        migrations.AddField(
            model_name='sizeimage',
            name='logo_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_products', to='products.products', verbose_name='Логотип продукта'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='undercategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
