# Generated by Django 3.2.16 on 2024-06-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240628_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeimage',
            options={'verbose_name': 'Изображения продукта', 'verbose_name_plural': 'Все изображения продуктов'},
        ),
        migrations.AlterModelOptions(
            name='undercategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='current_category',
        ),
        migrations.AddField(
            model_name='products',
            name='current_under_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_under_category', to='products.undercategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='undercategory',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='сategory', to='products.category'),
        ),
        migrations.AlterField(
            model_name='sizeimage',
            name='picture_size_1',
            field=models.ImageField(default=None, null=True, upload_to='recipes/size_1/', verbose_name='Размер-1'),
        ),
        migrations.AlterField(
            model_name='sizeimage',
            name='picture_size_2',
            field=models.ImageField(default=None, null=True, upload_to='recipes/size_2/', verbose_name='Размер-2'),
        ),
        migrations.AlterField(
            model_name='sizeimage',
            name='picture_size_3',
            field=models.ImageField(default=None, null=True, upload_to='recipes/size_3/', verbose_name='Размер-3'),
        ),
        migrations.DeleteModel(
            name='CategoryToUnderCategory',
        ),
    ]
