# Generated by Django 3.2.16 on 2024-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240628_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeimage',
            name='size_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/size_1/', verbose_name='Размер-1'),
        ),
        migrations.AlterField(
            model_name='sizeimage',
            name='size_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/size_2/', verbose_name='Размер-2'),
        ),
        migrations.AlterField(
            model_name='sizeimage',
            name='size_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/size_3/', verbose_name='Размер-3'),
        ),
    ]
